### PR TITLE
strip microseconds from last reboot

### PR DESCRIPTION
**Pull request by wrkn4alivn**
To fix https://github.com/home-assistant/core/issues/35954

### CODE REVIEW

**Review by dshokouhi — COMMENTED** [review]
I tried to test this change in my HA dev system but it gave me a start up error.  Are we missing something else?

```
2020-05-21 18:40:31 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up obihai platform for sensor
Traceback (most recent call last):
  File "/mnt/c/dev/home-assistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/c/dev/home-assistant/homeassistant/components/obihai/sensor.py", line 53, in setup_platform
    services = pyobihai.get_state()
  File "/mnt/c/dev/home-assistant/venv/lib/python3.7/site-packages/pyobihai/__init__.py", line 60, in get_state
    state = state - datetime.timedelta(microseconds=state.microseconds)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
```

**Comment by wrkn4alivn** [comment]
Yes, sorry I don't have a dev environment set up so I was relying on a couple of quick lines in the notebook. Should work now.

**Comment by dshokouhi** [comment]
Ok the error is gone however the sensor seems to still be updating sporadically, it keeps jumping between these values: 

`2020-05-09T00:43:09`

`2020-05-09T00:43:08`

Are you seeing this on your end too?  Do we need to round up the value maybe?  Also thanks for your help on this 🙏

**Comment by wrkn4alivn** [comment]
Ah yes, this is because the `utcnow()` call and the `UpTime` value from Obi don't increment to the next second at the exact same time. Let me think for a bit on how to resolve this.

**Comment by wrkn4alivn** [comment]
OK, 3rd time is the charm? Couldn't really think of a way to handle it other than to just keep track of the prior Last Reboot date.

**Comment by dshokouhi** [comment]
So it does still update but nowhere near as frequently as before.  This was about 1 hour on the graph and it still varies by 1 second.  So definitely an improvement, I will leave it to you if you want to make more changes or call it good :)

image

**Comment by wrkn4alivn** [comment]
Thanks for checking it. I made one more tweak. Also, I left some explanatory notes in the last commit. I'm good with this change.

**Review by dshokouhi — APPROVED** [review]
Thank you seems to be working much better now!

image

Will package up a release shortly, I'll comment back here when its done if you want to push to HA.

**Comment by dshokouhi** [comment]
Version 1.2.2 is up on pypi :)  Let me know if you want to submit a PR to HA.

**Pull request merged**
