### PR TITLE
Add Timezone to Last Reboot

### PR DESCRIPTION
**Pull request by wrkn4alivn**
Still seeing weird behavior (e.g. **Obhai Last Reboot** in the future/past) where HA local time is offset from UTC:
image

Looked at the [python docs](https://docs.python.org/3/library/datetime.html), turns out that there is a different recommended approach to getting current time, so this PR uses that. Result:
image

### CODE REVIEW

**Comment by dshokouhi** [comment]
Thanks again! Testing this now, looks like there is a conflict with the files we'll need to resolve that before we can merge

**Comment by wrkn4alivn** [comment]
Ok not sure how to resolve the conflict, I'm not a git expert. Is that
something I did wrong and need to fix?

**Comment by dshokouhi** [comment]
Well the diff doesn't look right but the file seems to be ok lol

**Comment by dshokouhi** [comment]
@wrkn4alivn 1.2.3 is now on pypi, for future PR's please use a new branch based off `master` so we can avoid the conflicts :)

**Comment by wrkn4alivn** [comment]
Ah OK got it, will remember that, thanks!

I just updated my prod instance to 1.2.3 to make sure its looking good. I'm
assuming to update HA I just need to submit a PR to change the version
number in manifest.json, is that correct?

**Comment by dshokouhi** [comment]
After you update the manifest.json there is a script that needs to be ran to update HA requirements

```New dependencies are added to requirements_all.txt (if applicable), using python3 -m script.gen_requirements_all```

its part of the development checklist: https://developers.home-assistant.io/docs/development_checklist

**Comment by dshokouhi** [comment]
@wrkn4alivn were you still going to update HA with the version bump or should I?

**Comment by wrkn4alivn** [comment]
Apologies for disappearing. Please go ahead if you're willing, I've been
distracted with other things.... Thanks for all your help!

**Comment by dshokouhi** [comment]
no problem ill get it updated in HA....thanks for your contribution!!

**Pull request merged**
